imports:
- path: instance-template.jinja

resources:
# Creating Network for our deployment
- name: mypronetwork
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: true

- name: mypronetwork-allow-http-ssh-rdp-icmp
# Firewall rule for allowing http-ssh-rdp and icmp
  type: compute.v1.firewall
  properties:
    network: $(ref.mypronetwork.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    allowed:
    - IPProtocol: TCP
      ports: [22,80,3389]
    - IPProtocol: ICMP

- name: mypronetwork-wordpress-firewall-rule
# firewall rule for wordpress with target
  type: compute.v1.firewall
  properties:
    network: $(ref.mypronetwork.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    targetTags: ["wordpress"]
    allowed:
    - IPProtocol: TCP
      ports: ["80"]

- name: my-wordpress-template
# wordpress template
  type: instance-template.jinja
  properties:
    zone: us-central1-a
    machineType: e2-medium
    network: $(ref.mypronetwork.selfLink)
    subnetwork: regions/us-central1/subnetworks/mypronetwork